name: Build Test and Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update Versions
      env:
        VERSION_PREFIX: 0.8
        VERSION_SUFFIX: ${{github.run_number}}
      run: |
        VERSION=$VERSION_PREFIX.$VERSION_SUFFIX
        sed -i bak "s:<Version>1.0.0</Version>:<Version>$VERSION</Version>:g" Cli/Cli.csproj
        sed -i bak "s:<Version>1.0.0</Version>:<Version>$VERSION</Version>:g" Iril/Iril.csproj
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.400
    - name: Install ILSpy
      run: dotnet tool install ilspycmd -g
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: |
        cd Tests
        dotnet test -c Release --no-build --verbosity normal
    - name: Package
      run: |
        mkdir PackageOut
        cd Cli
        dotnet pack -c Release
        cp bin/Release/*.nupkg ../PackageOut
    - name: Upload Package
      uses: actions/upload-artifact@master
      with:
        path: PackageOut
